### ISSUE TITLE
Link unfurling in Slack

### ISSUE THREAD

**Issue by nolanlum** [nolanlum/notskype-qdb#35]
This is so underwhelming:

![](https://pshuu.moe/1D3/YsPzKX.png)

We need to add to the quote permalink SSR at the very least FB OpenGraph tags, preferably Twitter Card tags as well so we can add metadata. 

See https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254 for more info.

**Comment by Adjective-Object** [comment]
I can tackle this tonight/tomorrow probably

**Comment by Adjective-Object** [comment]
closed by #36
